-- Helper array for int -> string
BLIP_IDS = {
    [1] = "debug", -- standard
    [2] = "debug", -- bigblip
    [3] = "debug", -- police officer
    [4] = "", -- police area (no icon for this, it's an aeo)
    [5] = "debug", -- squre
    [6] = "normal", -- player
    [7] = "debug", -- north
    [8] = "waypoint",
    [9] = "debug", -- big circle
    [10] = "debug", -- big circle outline
    [11] = "debug", -- arrow up outline
    [12] = "debug", -- arrow down outline
    [13] = "debug", -- arrow up
    [14] = "debug", -- arrow down
    [15] = "helicopter",
    [16] = "jet",
    [17] = "debug", -- number 1
    [18] = "debug", -- 2
    [19] = "debug", -- 3
    [20] = "debug", -- 4
    [21] = "debug", -- 5
    [22] = "debug", -- 6
    [23] = "debug", -- 7
    [24] = "debug", -- 8
    [25] = "debug", -- 9
    [26] = "debug", -- number 10
    [27] = "debug", -- gta online crew
    [28] = "debug", -- gta online friendly
    [36] = "lift",
    [38] = "race", -- raceFinish
    [40] = "safehouse",
    [41] = "debug", -- police officer 2
    [42] = "policeCar", -- police car dot
    [43] = "helicopter", -- police helicopter
    [47] = "speech", -- chat bubble
    [50] = "garage", -- garage 2
    [51] = "pill", -- drugs
    [52] = "shop", -- store
    [56] = "policeCar",
    [58] = "debug", -- police player
    [60] = "policeStation",
    [61] = "hospital",
    [64] = "helicopter",
    [65] = "question", -- StrangersAndFreaks
    [66] = "moneyTuck", -- ArmoredTruck
    [68] = "towTruck",
    [71] = "sissors", -- barber
    [72] = "losSantosCustoms",
    [73] = "clothes",
    [75] = "tattoo", -- TattooParlor
    [76] = "simeon",
    [77] = "lester",
    [78] = "michael",
    [79] = "trevor",
    [84] = "deathmatch", -- rampage
    [85] = "vinewoodTours",
    [86] = "franklin", -- lamar
    [88] = "franklin",
    [89] = "chinese",
    [90] = "airport",
    [93] = "bar",
    [94] = "parachute", -- BaseJump
    [100] = "carWash",
    [102] = "comedyClub",
    [103] = "darts", -- dart
    [106] = "fib",
    [108] = "dollarSign",
    [109] = "golf",
    [110] = "ammuNation",
    [112] = "exile",
    [119] = "gunRange", -- ShootingRange
    [120] = "solomon",
    [121] = "stripClub",
    [122] = "tennis",
    [126] = "sprint", -- Triathlon
    [127] = "atvRace", -- OffRoadRaceFinish
    [134] = "key",
    [135] = "movieTheater",
    [136] = "music",
    [140] = "marijuana",
    [141] = "animal", -- Hunting
    [147] = "armsTraffickingGround",
    [149] = "debug", -- nigel
    [150] = "debug", -- AssaultRifle
    [151] = "debug", -- Bat
    [152] = "debug", -- Grenade
    [153] = "debug", -- Health
    [154] = "debug", -- Knife
    [155] = "debug", -- Molotov
    [156] = "debug", -- Pistol
    [156] = "debug", -- RPG
    [158] = "debug", -- Shotgun
    [159] = "debug", -- SMG
    [160] = "debug", -- Sniper
    [161] = "debug", -- SonicWave (wtf?)
    [162] = "pointOfInterest",
    [163] = "gtaPassive", -- GTAOPassive
    [164] = "gtaUsingMenu", -- GTAOUsingMenu
    [171] = "cuffs", -- Link
    [173] = "debug", -- Minigun
    [174] = "debug", -- GrenadeLauncher
    [175] = "armour", -- armour
    [176] = "castle",
    [184] = "camera",
    [188] = "cuffs", -- Handcuffs
    [197] = "yoga",
    [198] = "cab",
    [199] = "debug", -- number 11
    [200] = "debug", -- 12
    [201] = "debug", -- 13
    [202] = "debug", -- 14
    [203] = "debug", -- 15
    [204] = "debug", -- number 16
    [205] = "shrink",
    [206] = "epsilon", -- epsilon
    [225] = "personalCar", -- PersonalVehicleCar
    [226] = "personalBike", -- PersonalVehicleBike
    [237] = "jail", -- Custody
    [251] = "armsTraffickingAir",
    [266] = "fairground",
    [267] = "propertyManagement",
    [269] = "alturist",
    [270] = "debug", -- Enemy
    [273] = "debug", -- Chop
    [274] = "dead",
    [279] = "hooker",
    [280] = "debug", -- Friend
    [303] = "debug", -- BountyHit
    [304] = "gtaMission", -- GTAOMission
    [305] = "gtaSurvival", -- GTAOSurvival
    [306] = "debug", -- CrateDrop
    [307] = "debug", -- PlaneDrop
    [308] = "debug", -- Sub(marine)
    [309] = "race",
    [310] = "deathmatch",
    [311] = "debug", -- ArmWrestling
    [313] = "gunRange", -- AmmuNationShootingRange
    [314] = "debug", -- RaceAir
    [315] = "debug", -- RaceCar
    [316] = "debug", -- RaceSea
    [318] = "debug", -- GarbageTruck
    [350] = "garageForSale", -- SafehouseForSale
    [351] = "package",
    [352] = "debug", -- MartinMadrazo
    [353] = "helecopter", -- EnemyHelicopter
    [354] = "debug", -- Boost
    [355] = "debug", -- Devin
    [356] = "debug", -- Marina
    [357] = "garage",
    [358] = "golf", -- GolfFlag
    [359] = "airport", -- Hanger
    [360] = "debug", -- Helipad
    [361] = "jerryCan",
    [362] = "debug", -- Masks
    [363] = "heist", -- HeistSetup
    [364] = "debug", -- Incapacitated
    [365] = "debug", -- PickupSpawn
    [366] = "debug", -- BoilerSuit
    [367] = "debug", -- Completed
    [368] = "debug", -- Rockets
    [369] = "garageForSale",
    [370] = "garageForSale", -- HelipadForSale
    [371] = "garageForSale", -- MarinaForSale
    [374] = "debug", -- Business
    [375] = "garageForSale", -- BusinessForSale
    [376] = "debug", -- RaceBike
    [377] = "parachute",
    [378] = "deathmatch", -- TeamDeathmatch
    [379] = "debug", --RaceFoot
    [380] = "deathmatch", -- VehicleDeathmatch
    [381] = "debug", -- Barry
    [382] = "debug", -- Dom
    [383] = "debug", -- MaryAnn
    [384] = "debug", -- Cletus
    [385] = "debug", -- Josh
    [386] = "debug", -- Minute
    [387] = "debug", -- Omega
    [388] = "debug", -- Tonya
    [389] = "debug", -- Paparazzo
    [390] = "debug", -- Crosshair,
    [398] = "debug", -- Creator,
    [399] = "debug", -- CreatorDirection,
    [400] = "debug", -- Abigail,
    [401] = "debug", -- Blimp,
    [402] = "debug", -- Repair,
    [403] = "debug", -- Testosterone,
    [404] = "debug", -- Dinghy,
    [405] = "debug", -- Fanatic,
    [407] = "debug", -- Information,
    [408] = "debug", -- CaptureBriefcase,
    [409] = "debug", -- LastTeamStanding,
    [410] = "boat", -- Boat,
    [411] = "debug", -- CaptureHouse,
    [415] = "jerryCan", -- JerryCan2,
    [416] = "debu", -- RP,
    [417] = "safehouse", -- GTAOPlayerSafehouse,
    [418] = "debug", -- GTAOPlayerSafehouseDead,
    [419] = "debug", -- CaptureAmericanFlag,
    [420] = "debug", -- CaptureFlag,
    [421] = "debug", -- Tank,
    [422] = "helicopter", -- HelicopterAnimated,
    [423] = "jet", -- Plane,
    [425] = "debug", -- PlayerNoColor,
    [426] = "debug", -- GunCar,
    [427] = "boat", -- Speedboat,
    [428] = "heist", -- Heist,
    [430] = "debug", -- Stopwatch,
    [431] = "debug", -- DollarSignCircled,
    [432] = "debug", -- Crosshair2,
    [434] = "debug", -- DollarSignSquared
    [478] = "debug" -- CeoCrate
}
